Realización del Objetivo 4
Olasergiolas/Go-AutoEQ pull request #33
Opened 2021-11-05 20:09 UTC by Olasergiolas

Para este objetivo no solo se han realizado una serie de unit tests para comprobar la lectura de archivos de configuración AutoEQ sino que también se ha avanzado bastante con la lógica de negocio de la aplicación, siendo ahora capaces de generar perfiles de ecualización compatibles con el software de EasyEffects.

2021-11-05 20:15 UTC, Olasergiolas commented
Listo para revisión.

2021-11-09 13:06 UTC, JJ requested changes
No has justificado ni el marco de test ni la biblioteca elegida. Y ya os he dicho varias veces que es mala práctica desde un solo commit referenciar varios issues. Cada issue debe tener su commit, para que quede claro qué problema se está resolviendo y cómo se resuelve.

2021-11-09 13:24 UTC, Olasergiolas commented
> No has justificado ni el marco de test ni la biblioteca elegida. Y ya os he dicho varias veces que es mala práctica desde un solo commit referenciar varios issues. Cada issue debe tener su commit, para que quede claro qué problema se está resolviendo y cómo se resuelve.

Toda la razón, resulta mucho más claro de esa forma y así lo haré de ahora en adelante. Respecto a la documentación, en cuanto saque un rato libre la amplío 👍.

2021-11-09 13:28 UTC, JJ commented
> > No has justificado ni el marco de test ni la biblioteca elegida. Y ya os he dicho varias veces que es mala práctica desde un solo commit referenciar varios issues. Cada issue debe tener su commit, para que quede claro qué problema se está resolviendo y cómo se resuelve.
> 
> Toda la razón, resulta mucho más claro de esa forma y así lo haré de ahora en adelante. Respecto a la documentación, en cuanto saque un rato libre la amplío +1.

Gracias, Sergio. No hace falta más que un párrafo describiendo cada uno.

2021-11-11 18:25 UTC, Olasergiolas commented
Listo para revisión @JJ

2021-11-11 19:49 UTC, JJ approved these changes
:clap:

2021-11-11 19:51 UTC, merged