[IV-21-22] Realización del Objetivo 6
Olasergiolas/Go-AutoEQ pull request #46
Opened 2021-12-03 19:12 UTC by Olasergiolas

Para este objetivo se ha realizado lo siguiente:
- Se añade la configuración necesaria para hacer uso de los sistemas de integración continua Circle CI y Github Actions.
- Comprobación del correcto funcionamiento de ambos sistemas y de la Checks API.
- Se amplía la documentación para dejar reflejada la justificación técnica respecto a la elección de estos sistemas.

2021-12-03 19:16 UTC, Olasergiolas commented
¡Listo para revisión!

2021-12-07 19:24 UTC, JJ requested changes
El milestone no incluye esto como parte del producto mínimamente viable.

2021-12-08 15:58 UTC, Olasergiolas commented
> El milestone no incluye esto como parte del producto mínimamente viable.

Cierto, se me había pasado reflejar el contenido del objetivo en los milestone. Debería de estar ya solucionado.

2021-12-09 19:50 UTC, JJ approved these changes
:+1:

2021-12-10 07:35 UTC, merged